jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "09:15:07:d2:df:bb:e3:a5:de:f6:c7:3a:d1:f9:43:cc"
      - run: ssh -o StrictHostKeyChecking=no radio@radio.intruder.network "ls"
